### PR TITLE
Improvements to content view

### PR DESCRIPTION
**Pull request by mmstick**
- Make the list view scrollable
- Place list items into a list column
- Improve styling of list item buttons
- Minor refactoring

### CODE REVIEW

**Comment by mmstick** [comment]
There are some oddities I found that will require adjustments inside libcosmic.

**Comment by edfloreshz** [comment]
Thanks! 🎉 

What specifically needs adjustment?

**Comment by mmstick** [comment]
I definitely need to finish the list view widget and its button styles. The list column is adding some extra padding on the top and bottom that shouldn't be there, or at lest be configurable. The icon button is no longer as round as it used to be. There's also some layer container component theme issues.

**Comment by mmstick** [comment]
Should empty lists also show the header?

**Comment by edfloreshz** [comment]
To maintain consistency between lists I think they should.

**Comment by edfloreshz** [comment]
Implemented in #3

**Pull request merged**
